// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationhistory"
)

// LocationHistoryCreate is the builder for creating a LocationHistory entity.
type LocationHistoryCreate struct {
	config
	mutation *LocationHistoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LocationHistoryCreate) SetCreatedAt(v time.Time) *LocationHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LocationHistoryCreate) SetNillableCreatedAt(v *time.Time) *LocationHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LocationHistoryCreate) SetUpdatedAt(v time.Time) *LocationHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LocationHistoryCreate) SetNillableUpdatedAt(v *time.Time) *LocationHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *LocationHistoryCreate) SetEntityID(v uuid.UUID) *LocationHistoryCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetLocationID sets the "location_id" field.
func (_c *LocationHistoryCreate) SetLocationID(v uuid.UUID) *LocationHistoryCreate {
	_c.mutation.SetLocationID(v)
	return _c
}

// SetMovedIn sets the "moved_in" field.
func (_c *LocationHistoryCreate) SetMovedIn(v time.Time) *LocationHistoryCreate {
	_c.mutation.SetMovedIn(v)
	return _c
}

// SetMovedOut sets the "moved_out" field.
func (_c *LocationHistoryCreate) SetMovedOut(v time.Time) *LocationHistoryCreate {
	_c.mutation.SetMovedOut(v)
	return _c
}

// SetNillableMovedOut sets the "moved_out" field if the given value is not nil.
func (_c *LocationHistoryCreate) SetNillableMovedOut(v *time.Time) *LocationHistoryCreate {
	if v != nil {
		_c.SetMovedOut(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LocationHistoryCreate) SetID(v uuid.UUID) *LocationHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LocationHistoryCreate) SetNillableID(v *uuid.UUID) *LocationHistoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_c *LocationHistoryCreate) SetEntity(v *Entity) *LocationHistoryCreate {
	return _c.SetEntityID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_c *LocationHistoryCreate) SetLocation(v *Entity) *LocationHistoryCreate {
	return _c.SetLocationID(v.ID)
}

// Mutation returns the LocationHistoryMutation object of the builder.
func (_c *LocationHistoryCreate) Mutation() *LocationHistoryMutation {
	return _c.mutation
}

// Save creates the LocationHistory in the database.
func (_c *LocationHistoryCreate) Save(ctx context.Context) (*LocationHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LocationHistoryCreate) SaveX(ctx context.Context) *LocationHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LocationHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := locationhistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := locationhistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := locationhistory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LocationHistoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LocationHistory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LocationHistory.updated_at"`)}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "LocationHistory.entity_id"`)}
	}
	if _, ok := _c.mutation.LocationID(); !ok {
		return &ValidationError{Name: "location_id", err: errors.New(`ent: missing required field "LocationHistory.location_id"`)}
	}
	if _, ok := _c.mutation.MovedIn(); !ok {
		return &ValidationError{Name: "moved_in", err: errors.New(`ent: missing required field "LocationHistory.moved_in"`)}
	}
	if len(_c.mutation.EntityIDs()) == 0 {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required edge "LocationHistory.entity"`)}
	}
	if len(_c.mutation.LocationIDs()) == 0 {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required edge "LocationHistory.location"`)}
	}
	return nil
}

func (_c *LocationHistoryCreate) sqlSave(ctx context.Context) (*LocationHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LocationHistoryCreate) createSpec() (*LocationHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &LocationHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(locationhistory.Table, sqlgraph.NewFieldSpec(locationhistory.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(locationhistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(locationhistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.MovedIn(); ok {
		_spec.SetField(locationhistory.FieldMovedIn, field.TypeTime, value)
		_node.MovedIn = value
	}
	if value, ok := _c.mutation.MovedOut(); ok {
		_spec.SetField(locationhistory.FieldMovedOut, field.TypeTime, value)
		_node.MovedOut = &value
	}
	if nodes := _c.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationhistory.EntityTable,
			Columns: []string{locationhistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationhistory.LocationTable,
			Columns: []string{locationhistory.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LocationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LocationHistoryCreateBulk is the builder for creating many LocationHistory entities in bulk.
type LocationHistoryCreateBulk struct {
	config
	err      error
	builders []*LocationHistoryCreate
}

// Save creates the LocationHistory entities in the database.
func (_c *LocationHistoryCreateBulk) Save(ctx context.Context) ([]*LocationHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LocationHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocationHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LocationHistoryCreateBulk) SaveX(ctx context.Context) []*LocationHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
