// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationhistory"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// LocationHistoryUpdate is the builder for updating LocationHistory entities.
type LocationHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *LocationHistoryMutation
}

// Where appends a list predicates to the LocationHistoryUpdate builder.
func (_u *LocationHistoryUpdate) Where(ps ...predicate.LocationHistory) *LocationHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationHistoryUpdate) SetUpdatedAt(v time.Time) *LocationHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *LocationHistoryUpdate) SetEntityID(v uuid.UUID) *LocationHistoryUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *LocationHistoryUpdate) SetNillableEntityID(v *uuid.UUID) *LocationHistoryUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *LocationHistoryUpdate) SetLocationID(v uuid.UUID) *LocationHistoryUpdate {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *LocationHistoryUpdate) SetNillableLocationID(v *uuid.UUID) *LocationHistoryUpdate {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// SetMovedOut sets the "moved_out" field.
func (_u *LocationHistoryUpdate) SetMovedOut(v time.Time) *LocationHistoryUpdate {
	_u.mutation.SetMovedOut(v)
	return _u
}

// SetNillableMovedOut sets the "moved_out" field if the given value is not nil.
func (_u *LocationHistoryUpdate) SetNillableMovedOut(v *time.Time) *LocationHistoryUpdate {
	if v != nil {
		_u.SetMovedOut(*v)
	}
	return _u
}

// ClearMovedOut clears the value of the "moved_out" field.
func (_u *LocationHistoryUpdate) ClearMovedOut() *LocationHistoryUpdate {
	_u.mutation.ClearMovedOut()
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *LocationHistoryUpdate) SetEntity(v *Entity) *LocationHistoryUpdate {
	return _u.SetEntityID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_u *LocationHistoryUpdate) SetLocation(v *Entity) *LocationHistoryUpdate {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the LocationHistoryMutation object of the builder.
func (_u *LocationHistoryUpdate) Mutation() *LocationHistoryMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *LocationHistoryUpdate) ClearEntity() *LocationHistoryUpdate {
	_u.mutation.ClearEntity()
	return _u
}

// ClearLocation clears the "location" edge to the Entity entity.
func (_u *LocationHistoryUpdate) ClearLocation() *LocationHistoryUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LocationHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LocationHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := locationhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationHistoryUpdate) check() error {
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationHistory.entity"`)
	}
	if _u.mutation.LocationCleared() && len(_u.mutation.LocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationHistory.location"`)
	}
	return nil
}

func (_u *LocationHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationhistory.Table, locationhistory.Columns, sqlgraph.NewFieldSpec(locationhistory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(locationhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MovedOut(); ok {
		_spec.SetField(locationhistory.FieldMovedOut, field.TypeTime, value)
	}
	if _u.mutation.MovedOutCleared() {
		_spec.ClearField(locationhistory.FieldMovedOut, field.TypeTime)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationhistory.EntityTable,
			Columns: []string{locationhistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationhistory.EntityTable,
			Columns: []string{locationhistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationhistory.LocationTable,
			Columns: []string{locationhistory.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationhistory.LocationTable,
			Columns: []string{locationhistory.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LocationHistoryUpdateOne is the builder for updating a single LocationHistory entity.
type LocationHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationHistoryUpdateOne) SetUpdatedAt(v time.Time) *LocationHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *LocationHistoryUpdateOne) SetEntityID(v uuid.UUID) *LocationHistoryUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *LocationHistoryUpdateOne) SetNillableEntityID(v *uuid.UUID) *LocationHistoryUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *LocationHistoryUpdateOne) SetLocationID(v uuid.UUID) *LocationHistoryUpdateOne {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *LocationHistoryUpdateOne) SetNillableLocationID(v *uuid.UUID) *LocationHistoryUpdateOne {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// SetMovedOut sets the "moved_out" field.
func (_u *LocationHistoryUpdateOne) SetMovedOut(v time.Time) *LocationHistoryUpdateOne {
	_u.mutation.SetMovedOut(v)
	return _u
}

// SetNillableMovedOut sets the "moved_out" field if the given value is not nil.
func (_u *LocationHistoryUpdateOne) SetNillableMovedOut(v *time.Time) *LocationHistoryUpdateOne {
	if v != nil {
		_u.SetMovedOut(*v)
	}
	return _u
}

// ClearMovedOut clears the value of the "moved_out" field.
func (_u *LocationHistoryUpdateOne) ClearMovedOut() *LocationHistoryUpdateOne {
	_u.mutation.ClearMovedOut()
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *LocationHistoryUpdateOne) SetEntity(v *Entity) *LocationHistoryUpdateOne {
	return _u.SetEntityID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_u *LocationHistoryUpdateOne) SetLocation(v *Entity) *LocationHistoryUpdateOne {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the LocationHistoryMutation object of the builder.
func (_u *LocationHistoryUpdateOne) Mutation() *LocationHistoryMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *LocationHistoryUpdateOne) ClearEntity() *LocationHistoryUpdateOne {
	_u.mutation.ClearEntity()
	return _u
}

// ClearLocation clears the "location" edge to the Entity entity.
func (_u *LocationHistoryUpdateOne) ClearLocation() *LocationHistoryUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// Where appends a list predicates to the LocationHistoryUpdate builder.
func (_u *LocationHistoryUpdateOne) Where(ps ...predicate.LocationHistory) *LocationHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LocationHistoryUpdateOne) Select(field string, fields ...string) *LocationHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LocationHistory entity.
func (_u *LocationHistoryUpdateOne) Save(ctx context.Context) (*LocationHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationHistoryUpdateOne) SaveX(ctx context.Context) *LocationHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LocationHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := locationhistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationHistoryUpdateOne) check() error {
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationHistory.entity"`)
	}
	if _u.mutation.LocationCleared() && len(_u.mutation.LocationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationHistory.location"`)
	}
	return nil
}

func (_u *LocationHistoryUpdateOne) sqlSave(ctx context.Context) (_node *LocationHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationhistory.Table, locationhistory.Columns, sqlgraph.NewFieldSpec(locationhistory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LocationHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, locationhistory.FieldID)
		for _, f := range fields {
			if !locationhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != locationhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(locationhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MovedOut(); ok {
		_spec.SetField(locationhistory.FieldMovedOut, field.TypeTime, value)
	}
	if _u.mutation.MovedOutCleared() {
		_spec.ClearField(locationhistory.FieldMovedOut, field.TypeTime)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationhistory.EntityTable,
			Columns: []string{locationhistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationhistory.EntityTable,
			Columns: []string{locationhistory.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationhistory.LocationTable,
			Columns: []string{locationhistory.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationhistory.LocationTable,
			Columns: []string{locationhistory.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LocationHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
