// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationhistory"
)

// LocationHistory is the model entity for the LocationHistory schema.
type LocationHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID uuid.UUID `json:"entity_id,omitempty"`
	// LocationID holds the value of the "location_id" field.
	LocationID uuid.UUID `json:"location_id,omitempty"`
	// MovedIn holds the value of the "moved_in" field.
	MovedIn time.Time `json:"moved_in,omitempty"`
	// MovedOut holds the value of the "moved_out" field.
	MovedOut *time.Time `json:"moved_out,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LocationHistoryQuery when eager-loading is set.
	Edges        LocationHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LocationHistoryEdges holds the relations/edges for other nodes in the graph.
type LocationHistoryEdges struct {
	// Entity holds the value of the entity edge.
	Entity *Entity `json:"entity,omitempty"`
	// Location holds the value of the location edge.
	Location *Entity `json:"location,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EntityOrErr returns the Entity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LocationHistoryEdges) EntityOrErr() (*Entity, error) {
	if e.Entity != nil {
		return e.Entity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "entity"}
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LocationHistoryEdges) LocationOrErr() (*Entity, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LocationHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case locationhistory.FieldCreatedAt, locationhistory.FieldUpdatedAt, locationhistory.FieldMovedIn, locationhistory.FieldMovedOut:
			values[i] = new(sql.NullTime)
		case locationhistory.FieldID, locationhistory.FieldEntityID, locationhistory.FieldLocationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LocationHistory fields.
func (_m *LocationHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case locationhistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case locationhistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case locationhistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case locationhistory.FieldEntityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value != nil {
				_m.EntityID = *value
			}
		case locationhistory.FieldLocationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field location_id", values[i])
			} else if value != nil {
				_m.LocationID = *value
			}
		case locationhistory.FieldMovedIn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field moved_in", values[i])
			} else if value.Valid {
				_m.MovedIn = value.Time
			}
		case locationhistory.FieldMovedOut:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field moved_out", values[i])
			} else if value.Valid {
				_m.MovedOut = new(time.Time)
				*_m.MovedOut = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LocationHistory.
// This includes values selected through modifiers, order, etc.
func (_m *LocationHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntity queries the "entity" edge of the LocationHistory entity.
func (_m *LocationHistory) QueryEntity() *EntityQuery {
	return NewLocationHistoryClient(_m.config).QueryEntity(_m)
}

// QueryLocation queries the "location" edge of the LocationHistory entity.
func (_m *LocationHistory) QueryLocation() *EntityQuery {
	return NewLocationHistoryClient(_m.config).QueryLocation(_m)
}

// Update returns a builder for updating this LocationHistory.
// Note that you need to call LocationHistory.Unwrap() before calling this method if this LocationHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LocationHistory) Update() *LocationHistoryUpdateOne {
	return NewLocationHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LocationHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LocationHistory) Unwrap() *LocationHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LocationHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LocationHistory) String() string {
	var builder strings.Builder
	builder.WriteString("LocationHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntityID))
	builder.WriteString(", ")
	builder.WriteString("location_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LocationID))
	builder.WriteString(", ")
	builder.WriteString("moved_in=")
	builder.WriteString(_m.MovedIn.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.MovedOut; v != nil {
		builder.WriteString("moved_out=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// LocationHistories is a parsable slice of LocationHistory.
type LocationHistories []*LocationHistory
