// Code generated by ent, DO NOT EDIT.

package locationhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldEntityID, v))
}

// LocationID applies equality check predicate on the "location_id" field. It's identical to LocationIDEQ.
func LocationID(v uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldLocationID, v))
}

// MovedIn applies equality check predicate on the "moved_in" field. It's identical to MovedInEQ.
func MovedIn(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldMovedIn, v))
}

// MovedOut applies equality check predicate on the "moved_out" field. It's identical to MovedOutEQ.
func MovedOut(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldMovedOut, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotIn(FieldEntityID, vs...))
}

// LocationIDEQ applies the EQ predicate on the "location_id" field.
func LocationIDEQ(v uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldLocationID, v))
}

// LocationIDNEQ applies the NEQ predicate on the "location_id" field.
func LocationIDNEQ(v uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNEQ(FieldLocationID, v))
}

// LocationIDIn applies the In predicate on the "location_id" field.
func LocationIDIn(vs ...uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIn(FieldLocationID, vs...))
}

// LocationIDNotIn applies the NotIn predicate on the "location_id" field.
func LocationIDNotIn(vs ...uuid.UUID) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotIn(FieldLocationID, vs...))
}

// MovedInEQ applies the EQ predicate on the "moved_in" field.
func MovedInEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldMovedIn, v))
}

// MovedInNEQ applies the NEQ predicate on the "moved_in" field.
func MovedInNEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNEQ(FieldMovedIn, v))
}

// MovedInIn applies the In predicate on the "moved_in" field.
func MovedInIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIn(FieldMovedIn, vs...))
}

// MovedInNotIn applies the NotIn predicate on the "moved_in" field.
func MovedInNotIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotIn(FieldMovedIn, vs...))
}

// MovedInGT applies the GT predicate on the "moved_in" field.
func MovedInGT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGT(FieldMovedIn, v))
}

// MovedInGTE applies the GTE predicate on the "moved_in" field.
func MovedInGTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGTE(FieldMovedIn, v))
}

// MovedInLT applies the LT predicate on the "moved_in" field.
func MovedInLT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLT(FieldMovedIn, v))
}

// MovedInLTE applies the LTE predicate on the "moved_in" field.
func MovedInLTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLTE(FieldMovedIn, v))
}

// MovedOutEQ applies the EQ predicate on the "moved_out" field.
func MovedOutEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldEQ(FieldMovedOut, v))
}

// MovedOutNEQ applies the NEQ predicate on the "moved_out" field.
func MovedOutNEQ(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNEQ(FieldMovedOut, v))
}

// MovedOutIn applies the In predicate on the "moved_out" field.
func MovedOutIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIn(FieldMovedOut, vs...))
}

// MovedOutNotIn applies the NotIn predicate on the "moved_out" field.
func MovedOutNotIn(vs ...time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotIn(FieldMovedOut, vs...))
}

// MovedOutGT applies the GT predicate on the "moved_out" field.
func MovedOutGT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGT(FieldMovedOut, v))
}

// MovedOutGTE applies the GTE predicate on the "moved_out" field.
func MovedOutGTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldGTE(FieldMovedOut, v))
}

// MovedOutLT applies the LT predicate on the "moved_out" field.
func MovedOutLT(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLT(FieldMovedOut, v))
}

// MovedOutLTE applies the LTE predicate on the "moved_out" field.
func MovedOutLTE(v time.Time) predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldLTE(FieldMovedOut, v))
}

// MovedOutIsNil applies the IsNil predicate on the "moved_out" field.
func MovedOutIsNil() predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldIsNull(FieldMovedOut))
}

// MovedOutNotNil applies the NotNil predicate on the "moved_out" field.
func MovedOutNotNil() predicate.LocationHistory {
	return predicate.LocationHistory(sql.FieldNotNull(FieldMovedOut))
}

// HasEntity applies the HasEdge predicate on the "entity" edge.
func HasEntity() predicate.LocationHistory {
	return predicate.LocationHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntityWith applies the HasEdge predicate on the "entity" edge with a given conditions (other predicates).
func HasEntityWith(preds ...predicate.Entity) predicate.LocationHistory {
	return predicate.LocationHistory(func(s *sql.Selector) {
		step := newEntityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.LocationHistory {
	return predicate.LocationHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Entity) predicate.LocationHistory {
	return predicate.LocationHistory(func(s *sql.Selector) {
		step := newLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LocationHistory) predicate.LocationHistory {
	return predicate.LocationHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LocationHistory) predicate.LocationHistory {
	return predicate.LocationHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LocationHistory) predicate.LocationHistory {
	return predicate.LocationHistory(sql.NotPredicates(p))
}
